name: irctest with InspIRCd

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
          $GITHUB_WORKSPACE/inspircd
        key: ${{ runner.os }}-inspircd

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest -r requirements.txt

    - name: Checkout InspIRCd
      uses: actions/checkout@v2
      with:
        repository: inspircd/inspircd
        ref: v3.8.1
        path: inspircd

    - name: Build InspIRCd
      run: |
        cd $GITHUB_WORKSPACE/inspircd/
        patch src/inspircd.cpp < $GITHUB_WORKSPACE/inspircd_mainloop.patch
        ./configure --prefix=$HOME/.local/ --development
        make -j 4
        make install

    - name: Test with pytest
      run: |
        # testNoticeNonexistentChannel fails because of https://github.com/inspircd/inspircd/issues/1849
        # testDirectMessageEcho fails because of https://github.com/inspircd/inspircd/issues/1851
        # testKeyValidation fails because of https://github.com/inspircd/inspircd/issues/1850
        PATH=~/.local/bin:$PATH pytest --controller irctest.controllers.inspircd -k 'not Ergo and not deprecated and not strict and not testNoticeNonexistentChannel and not testDirectMessageEcho and not testKeyValidation'

